version: "3"
services:
  pgha-proxy:
    image: haproxy
    ports:
      - "5432:5432"
      - "5500:5500"
      - "8404:8404"
    restart: unless-stopped
    volumes:
      - ./haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
  pgha1:
    image: postgres
    environment:
      POSTGRES_PASSWORD: example
    restart: unless-stopped
    volumes:
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
  pgha2:
    image: postgres
    environment:
      POSTGRES_PASSWORD: example
    restart: unless-stopped
    volumes:
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
  pgha3:
    image: postgres
    environment:
      POSTGRES_PASSWORD: example
    restart: unless-stopped
    volumes:
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
